# Generated by Django 4.1.4 on 2022-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField(verbose_name="text")),
            ],
            options={
                "verbose_name": "Discription",
                "verbose_name_plural": "Discription",
            },
        ),
        migrations.CreateModel(
            name="Networks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nw_name", models.CharField(max_length=100, verbose_name="Network")),
                ("nw_link", models.CharField(max_length=200, verbose_name="link")),
                (
                    "nw_image",
                    models.ImageField(
                        height_field="50", upload_to="Networks_img", width_field="50"
                    ),
                ),
            ],
        ),
    ]
