# Generated by Django 4.1.4 on 2022-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_discription_dics_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discription",
            name="dics_image",
            field=models.ImageField(
                default="-",
                height_field="300",
                null=True,
                upload_to="about_img",
                width_field="100",
            ),
        ),
    ]
