# Generated by Django 4.1.4 on 2022-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_discription_dics_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networks",
            options={"verbose_name": "Network", "verbose_name_plural": "Networks"},
        ),
        migrations.AlterField(
            model_name="discription",
            name="dics_image",
            field=models.ImageField(null=True, upload_to="about_img"),
        ),
        migrations.AlterField(
            model_name="networks",
            name="nw_image",
            field=models.ImageField(upload_to="Networks_img"),
        ),
    ]
