# Generated by Django 4.1.4 on 2022-12-19 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comp_name",
                    models.CharField(max_length=200, verbose_name="Name competenton"),
                ),
                (
                    "comp_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skills",
                        verbose_name="Competencies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competencies",
                "verbose_name_plural": "Competencies",
            },
        ),
    ]
