# Generated by Django 4.1.4 on 2022-12-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_competencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="skill_comp",
            field=models.TextField(default=2, verbose_name="Competencies"),
            preserve_default=False,
        ),
    ]
