# Generated by Django 4.1.4 on 2022-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_skills_skill_comp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="skill_comp",
            field=models.TextField(null=True, verbose_name="Competencies"),
        ),
        migrations.DeleteModel(
            name="Competencies",
        ),
    ]
