# Generated by Django 4.1.4 on 2022-12-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_name",
                    models.CharField(max_length=100, verbose_name="Name of resume"),
                ),
                (
                    "resume_language",
                    models.CharField(
                        max_length=100, verbose_name=" Language of resume"
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(upload_to="resume_files", verbose_name="File"),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resume",
            },
        ),
    ]
