# Generated by Django 4.1.4 on 2022-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edu_name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "edu_image",
                    models.ImageField(upload_to="edu_image", verbose_name="Image"),
                ),
                ("edu_disc", models.TextField(verbose_name="Discription")),
                (
                    "edu_start",
                    models.CharField(max_length=200, verbose_name="Start date"),
                ),
                ("edu_end", models.CharField(max_length=200, verbose_name="End date")),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
            },
        ),
    ]
