# Generated by Django 4.1.4 on 2022-12-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("art_title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "sub_title",
                    models.CharField(max_length=300, verbose_name="Sub title"),
                ),
                ("art_short_disc", models.TextField(verbose_name="Short disc")),
                (
                    "art_image",
                    models.ImageField(
                        upload_to="article_img", verbose_name="Article image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_img",
                    models.ImageField(
                        upload_to="article_body_img", verbose_name="Article image"
                    ),
                ),
                (
                    "photo_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.article",
                        verbose_name="Paragraph",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="Paragraphs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("par_text", models.TextField(verbose_name="Text")),
                (
                    "par_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.article",
                        verbose_name="Paragraph",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text",
                "verbose_name_plural": "Text",
            },
        ),
    ]
