# Generated by Django 4.1.4 on 2022-12-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraphs",
            name="par_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.article",
                verbose_name="Article",
            ),
        ),
    ]
