# Generated by Django 4.1.4 on 2022-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_paragraphs_par_binding_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paragraphs",
            options={"verbose_name": "Paragraph", "verbose_name_plural": "Paragraphs"},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AddField(
            model_name="article",
            name="link_to_github",
            field=models.CharField(
                default="-", max_length=300, verbose_name="Link to github"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="link_to_site",
            field=models.CharField(
                default="-", max_length=300, verbose_name="Link to site"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sub_title",
            field=models.CharField(
                default="-", max_length=300, verbose_name="Sub title"
            ),
        ),
        migrations.AlterField(
            model_name="paragraphs",
            name="par_text",
            field=models.TextField(verbose_name="Paragraph"),
        ),
    ]
