# Generated by Django 4.1.4 on 2022-12-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_title", models.CharField(max_length=300, verbose_name="Title")),
                ("mail_h1", models.CharField(max_length=300, verbose_name="h1 title")),
                ("mail_text", models.TextField(verbose_name="Text")),
            ],
            options={
                "verbose_name": "Title",
                "verbose_name_plural": "Titles",
            },
        ),
    ]
