# Generated by Django 4.1.4 on 2022-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_token", models.CharField(max_length=200, verbose_name="Token")),
                ("tg_chat", models.CharField(max_length=200, verbose_name="Chat")),
                ("tg_text", models.TextField(verbose_name="Text")),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
