# Generated by Django 4.1.4 on 2022-12-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_telesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msettings",
            options={"verbose_name": "Mail", "verbose_name_plural": "Mail"},
        ),
        migrations.AlterModelOptions(
            name="telesettings",
            options={"verbose_name": "Telegram", "verbose_name_plural": "Telegram"},
        ),
    ]
